# Generated by Django 3.2.8 on 2021-10-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.TextField(blank=True, null=True)),
                ('product_quantity', models.IntegerField(max_length=250)),
                ('product_bp', models.IntegerField(blank=True, null=True)),
                ('product_sp', models.IntegerField(blank=True, null=True)),
                ('product_payment', models.IntegerField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
