# Generated by Django 3.2.8 on 2021-10-18 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('product', '0002_alter_product_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_bp',
            new_name='buying_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_payment',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_quantity',
            new_name='selling_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_sp',
            new_name='spoilt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_desc',
        ),
        migrations.AddField(
            model_name='product',
            name='payment_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(to='store.Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
