# Generated by Django 3.2.8 on 2021-10-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
