# Generated by Django 3.2.8 on 2021-10-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_upload',
        ),
        migrations.AddField(
            model_name='product',
            name='date_received',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
