# Generated by Django 3.2.8 on 2021-10-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20211020_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_received',
        ),
    ]
