# Generated by Django 3.2.8 on 2021-10-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_received',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
    ]
