# Generated by Django 3.2.8 on 2021-10-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profilePic',
            new_name='profile_pic',
        ),
    ]
