# Generated by Django 3.2.8 on 2021-10-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset',
            field=models.CharField(default='hnnka5647301', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
