# Generated by Django 3.2.8 on 2021-10-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Merchant'), (2, 'Store_admin'), (3, 'Clerk')], default=3, null=True),
        ),
    ]
