# Generated by Django 3.2.8 on 2021-10-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.CreateModel(
            name='StoreAdmin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Merchant', 'merchant'), ('Store_admin', 'store_admin'), ('Clerk', 'clerk')], default='Clerk', max_length=255, null=True),
        ),
    ]
