# Generated by Django 3.2.8 on 2021-10-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('MERCHANT', 'Merchant'), ('STOREADMIN', 'Storeadmin'), ('CLERK', 'Clerk')], default='CLERK', max_length=255, null=True, verbose_name='role'),
        ),
    ]
