# Generated by Django 3.2.8 on 2021-10-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_user_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('MERCHANT', 'Merchant'), ('STOREADMIN', 'Storeadmin'), ('CLERK', 'Clerk')], default='MERCHANT', max_length=255, null=True, verbose_name='role'),
        ),
    ]
